const FINALFORMATE = {
  Dis_ID1: "Thiruvallur",
  Dis_ID2: "Chennai",
  Dis_ID3: "Kanchipuram",
  Dis_ID4: "Vellore",
  Dis_ID5: "Thiruvannamalai",
  Dis_ID6: "Viluppuram",
  Dis_ID7: "Salem",
  Dis_ID8: "Namakkal",
  Dis_ID9: "Erode",
  Dis_ID10: "Nilgiris",
  Dis_ID11: "Dindigul",
  Dis_ID12: "Karur",
  Dis_ID13: "Thiruchirapalli",
  Dis_ID14: "Perambalur",
  Dis_ID15: "Ariyalur",
  Dis_ID16: "Cuddalore",
  Dis_ID17: "Nagapattinam",
  Dis_ID18: "Thiruvarur",
  Dis_ID19: "Thanjavur",
  Dis_ID20: {
    District_Name: "Pudukkottai",
    Godowns: {
      Godown_ID01: {
        Godown_ID: 1,
        Godown: "Alangudi  (Tk)",
        PDS_Shops: {
          PDS_1: "Alangudi Amutham",
          PDS_2: "Alangudi -1",
          PDS_3: "Alangudi -2",
          PDS_4: "Kallalangudi",
          PDS_5: "Sikkappatti",
          PDS_6: "Alangadu",
          PDS_7: "Pallathividuthi",
          PDS_8: "Thoppukollai",
          PDS_9: "Kuppakudi",
          PDS_10: "Pathampatti",
          PDS_11: "Therkku Mellakkottai",
          PDS_12: "Melakottai",
          PDS_13: "Ayippatti",
          PDS_14: "Kovilur",
          PDS_15: "Othakadai",
          PDS_16: "K.V.Kottai",
          PDS_17: "Pudukkottaividuthi",
          PDS_18: "Melanemmakottai",
          PDS_19: "Arasatipatti",
          PDS_20: "Kummankulam",
          PDS_21: "Vellakulam",
          PDS_22: "Sooranviduthi",
          PDS_23: "Kalipullah Nagar",
          PDS_24: "Valluvar Mandram",
          PDS_25: "Kodikarampai",
          PDS_26: "Keeramankalam Ho",
          PDS_27: "Keeramankalam Pettai",
          PDS_28: "Keeramankalam South",
          PDS_29: "Seriyalur -1",
          PDS_30: "Seriyalur -2",
          PDS_31: "Pannankulam South",
          PDS_32: "Pannankulam North",
          PDS_33: "Nagaram HO",
          PDS_34: "Kulamangalam East",
          PDS_35: "Kulamangalam North",
          PDS_36: "Kulamangalam South",
          PDS_37: "Senthankudi",
          PDS_38: "Karambadadu 2",
          PDS_39: "Karambadadu -1",
          PDS_40: "M.Rasiyamangalam",
          PDS_41: "Pappanviduthi",
          PDS_42: "K.Rasiyamangalam",
          PDS_43: "Malavarayanpatti",
          PDS_44: "Vamban",
          PDS_45: "Brahathambalpuram",
          PDS_46: "Kothakottai",
          PDS_47: "Kayampatti",
          PDS_48: "Maichelpatti",
          PDS_49: "Thechinapuram 1",
          PDS_50: "Thechinapuram -2",
          PDS_51: "Thiruvarankulam",
          PDS_52: "Thethampatti",
          PDS_53: "Veppankudi",
          PDS_54: "Kaikuruchi",
          PDS_55: "Mettupatti",
          PDS_56: "Thirukattalai",
          PDS_57: "Vijayaragunatha Puram",
          PDS_58: "Neduvasal -Ho",
          PDS_59: "Pulichankadu",
          PDS_60: "Neduvasal Melpathi",
          PDS_61: "Anavayal -2",
          PDS_62: "Anavayal 1",
          PDS_63: "Andavarayapuram",
          PDS_64: "L.N.Puram",
          PDS_65: "Sundangivalasai",
          PDS_66: "Kothamangalam Ho",
          PDS_67: "Chithamparaviduthi",
          PDS_68: "Kothamangalam North",
          PDS_69: "Kothamangalam South",
          PDS_70: "Vadakadu Ho",
          PDS_71: "Vadakadu South",
          PDS_72: "Poochikadai",
          PDS_73: "Mangadu",
          PDS_74: "Melapullanviduthi",
          PDS_75: "Pullanviduthi",
          PDS_76: "Keelathur Samathuvapuram",
          PDS_77: "Keelathur",
          PDS_78: "Paraman Nagar (W)",
          PDS_79: "Poovarasakudi",
          PDS_80: "Vandakottai",
        },
      },

      Godown_ID02: {
        Godown_ID: 2,
        Godown: "Aranthangi (Tk)",
        PDS_Shops: {
          PDS_1: "Akki Bazar(Muslim Street) - I",
          PDS_2: "L.N.Puram Shop - I",
          PDS_3: "Gandhiboongasalai",
          PDS_4: "Akki Bazar(Muslim Street) - II",
          PDS_5: "L.N.Puram Shop - II",
          PDS_6: "V.O.C.Thidal(Amudham Shop)",
          PDS_7: "Thozhuvankadu",
          PDS_8: "Kollanvayal",
          PDS_9: "Silattur(Amudham Shop)",
          PDS_10: "Pudukkottai Road Shop",
          PDS_11: "Seenivasanpillai St.(Periyakadai Road)",
          PDS_12: "Agaram Shop",
          PDS_13: "Gangadarapuram",
          PDS_14: "Hospital Shop",
          PDS_15: "Vijayapuram",
          PDS_16: "Ambalpuram",
          PDS_17: "Mangalanadu North",
          PDS_18: "Mangalanadu",
          PDS_19: "Koothadivayal",
          PDS_20: "Mookkudi",
          PDS_21: "Valakudiyiruppu",
          PDS_22: "Annamalaiyan Kudieruppu",
          PDS_23: "Aliyanilai",
          PDS_24: "Kurunthirakottai",
          PDS_25: "Rajendrapuram",
          PDS_26: "Erukkalakottai",
          PDS_27: "Chettikkadu",
          PDS_28: "Merpanaikadu Pettai",
          PDS_29: "Merpanaikadu Ho",
          PDS_30: "Vembankudi",
          PDS_31: "Pandikudi",
          PDS_32: "Periyalur",
          PDS_33: "Poovathakudi",
          PDS_34: "Neivathali",
          PDS_35: "Arasarkulam Pettai",
          PDS_36: "Arasarkulam Keelpathi",
          PDS_37: "Arasarkulam Vadapathi",
          PDS_38: "Arasarkulam Ho",
          PDS_39: "Kodivayal",
          PDS_40: "Manivilanvayal",
          PDS_41: "Amarasimenthirapuram",
          PDS_42: "Avanathankottai",
          PDS_43: "Chittankadu",
          PDS_44: "Thirunalur North",
          PDS_45: "Thirunalur South",
          PDS_46: "Oorvani",
          PDS_47: "Samathuvapuram",
          PDS_48: "Pakkudi",
          PDS_49: "Amanji",
          PDS_50: "Alangudi",
          PDS_51: "Sengamari",
          PDS_52: "Narppavalakkudi",
          PDS_53: "Sirunattanvayal",
          PDS_54: "Kongudi",
          PDS_55: "Kulathur",
          PDS_56: "Nayakkarpatti",
          PDS_57: "Perumalpatti",
          PDS_58: "Alapiranthan",
          PDS_59: "Perunavalur",
          PDS_60: "Navinivayal",
          PDS_61: "Veeramangalam",
          PDS_62: "Sivanthankadu",
          PDS_63: "Pangayathankudi",
          PDS_64: "Vettanur",
          PDS_65: "Vellattumangalam",
          PDS_66: "Thedakki",
          PDS_67: "Adalaikalabairavapuram",
          PDS_68: "Nemmelikadu",
          PDS_69: "Ekaperumalur",
          PDS_70: "Ekanivayal",
          PDS_71: "Kandichankadu",
          PDS_72: "Ulakalathanvayal Pakuthi",
          PDS_73: "Ulakalathanvayal Ho",
          PDS_74: "Edayar",
          PDS_75: "Subramaniyapuram",
          PDS_76: "Mannakudi",
          PDS_77: "Pidarikkadu",
          PDS_78: "Chittakkanni",
          PDS_79: "Koohanur",
          PDS_80: "Kalakkudi",
          PDS_81: "Nagudi",
          PDS_82: "Ariyamaraikkadu",
          PDS_83: "Keelkudi",
          PDS_84: "Karavayal",
          PDS_85: "Maivayal",
          PDS_86: "Manavanallur",
          PDS_87: "Dharmarajanvayal",
          PDS_88: "Patharasankottai",
          PDS_89: "Athani",
          PDS_90: "Kalakkamangalam",
          PDS_91: "Thattanvayal",
          PDS_92: "Thiruvappadi",
          PDS_93: "Maruthankudi",
          PDS_94: "Mangudi",
          PDS_95: "Rethinakottai",
          PDS_96: "Nattumangalam",
          PDS_97: "Ettiyathali",
          PDS_98: "Vairivayal",
          PDS_99: "Melapattu",
          PDS_100: "Ayingudi",
          PDS_101: "Thondaiman Kudiyiruppu",
          PDS_102: "Vallavari",
          PDS_103: "Ramasamipuram",
          PDS_104: "Mathur",
          PDS_105: "Maramadakki",
          PDS_106: "Perunkadu",
          PDS_107: "Kovilvayal",
          PDS_108: "Thoothakkudi",
          PDS_109: "Melmangalam",
          PDS_110: "Valayanvayal",
          PDS_111: "Allaraimelavayal",
          PDS_112: "Paravakottai",
          PDS_113: "Sunayakkadu",
          PDS_114: "Chidambaraviduthi",
          PDS_115: "Kurumbur",
          PDS_116: "Thanthani",
        },
      },
      Godown_ID03: {
        Godown_ID: 3,
        Godown: "Avudaiyrkoil (Tk)",
        PDS_Shops: {
          PDS_1: "Avudaiyrkoil Amutham",
          PDS_2: "Mimisal Amutham",
          PDS_3: "Kulathukudierupu",
          PDS_4: "Avudaiyarkoil Hs",
          PDS_5: "Kulathukudierupu",
          PDS_6: "Pandipathiram",
          PDS_7: "Puniyavayal",
          PDS_8: "Elunoothimangalam",
          PDS_9: "Poovalur",
          PDS_10: "Piranthani",
          PDS_11: "Thalanur",
          PDS_12: "Kannakur",
          PDS_13: "Veelimangalam",
          PDS_14: "Amaradakki",
          PDS_15: "Veliyathur",
          PDS_16: "Sathakudi",
          PDS_17: "Seppavayal",
          PDS_18: "Thillaivayal",
          PDS_19: "Thirappidingi",
          PDS_20: "Mathagam",
          PDS_21: "Embal",
          PDS_22: "Thanigadu",
          PDS_23: "Ichikkotai",
          PDS_24: "Enangam",
          PDS_25: "Kurungalur",
          PDS_26: "Vellalavayal",
          PDS_27: "Arasur",
          PDS_28: "Thonnakkudi",
          PDS_29: "Thiruvakkudi",
          PDS_30: "Irumbanadu",
          PDS_31: "Kudikadu",
          PDS_32: "Muthuvalargudi",
          PDS_33: "Palavarasan",
          PDS_34: "Esamangalam",
          PDS_35: "Kidangivayal",
          PDS_36: "Keelkudi",
          PDS_37: "Vaatathur",
          PDS_38: "Kallakathan",
          PDS_39: "Pattamudaiyan",
          PDS_40: "Velivayal",
          PDS_41: "Vilanur",
          PDS_42: "Sattiyakudi",
          PDS_43: "Chinnapattamangalam",
          PDS_44: "Ponpethi",
          PDS_45: "Peranur",
          PDS_46: "Adambur",
          PDS_47: "Theeyur",
          PDS_48: "Kovanikidangu",
          PDS_49: "Senganam",
          PDS_50: "Thennamari",
          PDS_51: "Theeyathur",
          PDS_52: "Kathiramangalam",
          PDS_53: "Kulathur",
          PDS_54: "Sathiyadi",
          PDS_55: "Pallivayal",
          PDS_56: "Narasingapurm",
          PDS_57: "Soundaranayakipuram",
          PDS_58: "Kavathukudi",
          PDS_59: "Thanikamdan",
          PDS_60: "R.Pudupattinam",
          PDS_61: "Alathur",
          PDS_62: "Kadavakkottai",
          PDS_63: "Sirukadavakkottai",
          PDS_64: "Muthukuda",
          PDS_65: "Velivayal",
          PDS_66: "Gopalapattinam",
          PDS_67: "Nattanipurasakudi",
          PDS_68: "Arasanagaripattinam",
          PDS_69: "Velvarai",
          PDS_70: "Okkur",
          PDS_71: "Perunthamari",
          PDS_72: "Sananenthal",
          PDS_73: "Thunjanur",
          PDS_74: "Sithakur",
          PDS_75: "Karur",
          PDS_76: "Kumulur",
          PDS_77: "Konariyenthal",
          PDS_78: "Thiruppunavasal",
          PDS_79: "Kannamangalam",
          PDS_80: "Paraiyathur",
          PDS_81: "Veezhimar",
          PDS_82: "Puduvakkadu",
          PDS_83: "Gopalapattinam II",
        },
      },
      Godown_ID04: {
        Godown_ID: 4,
        Godown: "Gandarvakottai(Tk)",
        PDS_Shops: {
          PDS_1: "Amutham",
          PDS_2: "Kovilur",
          PDS_3: "Thurusupatti",
          PDS_4: "Pisanathur",
          PDS_5: "Akkachipatti",
          PDS_6: "Aravampatti",
          PDS_7: "Puthunagar",
          PDS_8: "Vadugapatti",
          PDS_9: "Meikudipatti",
          PDS_10: "Manganur",
          PDS_11: "Palaya Gandarvakottai",
          PDS_12: "Viralipatti",
          PDS_13: "Komapuram",
          PDS_14: "Nathamadipatti",
          PDS_15: "Nodiyur",
          PDS_16: "Kallupatti",
          PDS_17: "Savareyarpati",
          PDS_18: "Thachankuruchi",
          PDS_19: "Malayapati",
          PDS_20: "Kurumpoondi",
          PDS_21: "Manjapettai",
          PDS_22: "Kothampatti",
          PDS_23: "Thethuvasalpatti",
          PDS_24: "Muthugulam",
          PDS_25: "Ariyanipatti",
          PDS_26: "Matangal",
          PDS_27: "Veeradipatti",
          PDS_28: "Samathuvapuram",
          PDS_29: "Sokkampettai",
          PDS_30: "Kothagapatti",
          PDS_31: "Mohanur",
          PDS_32: "Sangamviduthi",
          PDS_33: "Kannukudipatti",
          PDS_34: "Kallakottai",
          PDS_35: "Ulavayal",
          PDS_36: "Kulanthurnayagarpatti",
          PDS_37: "Seveyrkudikadu",
          PDS_38: "Namburanpatti",
          PDS_39: "Pagatuvanpatti",
          PDS_40: "Nadupatti",
          PDS_41: "Sundampatti",
          PDS_42: "Sundampatti",
          PDS_43: "Katunaval",
          PDS_44: "Andanur",
          PDS_45: "Veladipatti",
          PDS_46: "Mullikapatti",
          PDS_47: "Nepugai",
          PDS_48: "Mangalakovil",
          PDS_49: "Vellalaviduthi",
          PDS_50: "Kendayampatti",
          PDS_51: "Thuvar",
          PDS_52: "Athangaraividuthi",
          PDS_53: "Valampatti",
          PDS_54: "Sothupalai",
        },
      },
      Godown_ID05: {
        Godown_ID: 5,
        Godown: "Illuppur (Tk)",
        PDS_Shops: {
          PDS_1: "Illuppur Amutham",
          PDS_2: "Illuppur - III",
          PDS_3: "Kottai Theru",
          PDS_4: "Illuppur - 1",
          PDS_5: "Illuppur - II",
          PDS_6: "Ennaikeelappatti",
          PDS_7: "Meyyanampatti",
          PDS_8: "Ennal Melappatti",
          PDS_9: "Kalluppatti",
          PDS_10: "Irunthirappatti",
          PDS_11: "Punginippatti",
          PDS_12: "Idaiyapatti",
          PDS_13: "Annavasal - I",
          PDS_14: "Indiracolony",
          PDS_15: "Idaiyar Street",
          PDS_16: "Sengappatti",
          PDS_17: "Annavasal - II",
          PDS_18: "Ariyur",
          PDS_19: "Panampatti",
          PDS_20: "Chithannavasal",
          PDS_21: "Mathiyanallur",
          PDS_22: "Panangudi",
          PDS_23: "Thachampatti",
          PDS_24: "Kalaikudippatti",
          PDS_25: "Vilathuppatti",
          PDS_26: "Meivazhisalai",
          PDS_27: "Keelakurichi",
          PDS_28: "Thayinippatti",
          PDS_29: "Perungudippatti",
          PDS_30: "Lekkanapatti",
          PDS_31: "Pasippatti",
          PDS_32: "Perumanadu",
          PDS_33: "Nilaiyappatti",
          PDS_34: "Pulvayal",
          PDS_35: "Agarappatti",
          PDS_36: "Vayalogam",
          PDS_37: "Keelapazhuvanji",
          PDS_38: "Kothandaramapuram",
          PDS_39: "Mangudi",
          PDS_40: "Marayappatti",
          PDS_41: "Kurukkappatti",
          PDS_42: "Sellukudi",
          PDS_43: "Ayingudi",
          PDS_44: "Thiruvengaivasal",
          PDS_45: "Perunjunai",
          PDS_46: "Sundarappatti",
          PDS_47: "Veerappatti - II",
          PDS_48: "Veerappatti - I",
          PDS_49: "Mukkanamalaippatti North",
          PDS_50: "Mukkanamalaippatti",
          PDS_51: "Vathirippatti",
          PDS_52: "Vellanjar",
          PDS_53: "Mahuthuppatti",
          PDS_54: "V. Udaiyanpatti",
          PDS_55: "Vettukadu",
          PDS_56: "Erukkumanippatti",
          PDS_57: "Kalingappatti",
          PDS_58: "Rappusal",
          PDS_59: "Uruvampatti",
          PDS_60: "Kudumiyanmalai",
          PDS_61: "Pudhur",
          PDS_62: "Visalur",
          PDS_63: "Seranur",
          PDS_64: "Pinnangudi",
          PDS_65: "Vannarappatti",
          PDS_66: "Parambur Panampatti",
          PDS_67: "Parambur",
          PDS_68: "Kadambarayanpatti",
          PDS_69: "Kilikkudi",
          PDS_70: "Kudalore",
          PDS_71: "Mampatti",
          PDS_72: "Peyal",
          PDS_73: "Thalinji",
          PDS_74: "Kadhavampatti",
          PDS_75: "Alathur",
          PDS_76: "Melakothirappatti",
          PDS_77: "Malaikudippatti",
          PDS_78: "Eswarankovil",
          PDS_79: "Periyakurumbapatti",
          PDS_80: "Kattakudi",
          PDS_81: "Thirunallur",
          PDS_82: "Vilappatti",
          PDS_83: "Nanguppatti",
          PDS_84: "Maruthanpatti",
          PDS_85: "Paiyur",
          PDS_86: "Pakkudi",
          PDS_87: "Thanngangudi",
          PDS_88: "Kongudippatti",
        },
      },
      Godown_ID06: {
        Godown_ID: 6,
        Godown: "Karambakudi (Tk)",
        PDS_Shops: {
          PDS_1: "Karambakudi Amutham",
          PDS_2: "Karambakudi North",
          PDS_3: "Karambakudi H.O",
          PDS_4: "Karambakudi Town",
          PDS_5: "Theethanviduthi",
          PDS_6: "Kulanthiranpattu",
          PDS_7: "Rangiyanviduthi",
          PDS_8: "Mela Ponnanviduthi",
          PDS_9: "Nainankollai",
          PDS_10: "Ponnanviduthi",
          PDS_11: "Mankottai Melapatti",
          PDS_12: "Nambanpatti Mankottai",
          PDS_13: "Andikonpatti",
          PDS_14: "Kalapam",
          PDS_15: "Mankottai Branch",
          PDS_16: "Vadakkalur",
          PDS_17: "Vandanviduthi",
          PDS_18: "Regunathapuram",
          PDS_19: "Puduviduthi",
          PDS_20: "Peyadipatti",
          PDS_21: "Mullankurichi - I",
          PDS_22: "Kottaikadu",
          PDS_23: "Mullankurichi",
          PDS_24: "Gopalapatti",
          PDS_25: "Kadukkakadu",
          PDS_26: "Kanakkankadu",
          PDS_27: "Vanakkankadu",
          PDS_28: "Karu Vadatheru",
          PDS_29: "Karu Souththeru",
          PDS_30: "Karu Keelatheru",
          PDS_31: "Pattathikadu",
          PDS_32: "Thirumanancheri",
          PDS_33: "Kurumbivayal",
          PDS_34: "Elakadividuthi",
          PDS_35: "Athiyadipatti",
          PDS_36: "Pallavarayanpathai",
          PDS_37: "Kolappanpatti",
          PDS_38: "M. Therkutheru",
          PDS_39: "Manamadai",
          PDS_40: "Odappaviduthi",
          PDS_41: "Sinnankonviduthi",
          PDS_42: "Pathuthakku",
          PDS_43: "Ambukoil",
          PDS_44: "Mailankonpatti",
          PDS_45: "Maruthankonviduthi",
          PDS_46: "Karambaviduthi",
          PDS_47: "Sevaipatti",
          PDS_48: "Ammanipattu",
          PDS_49: "Pilaviduthi",
          PDS_50: "Malaiyur",
          PDS_51: "Athiranviduthi",
          PDS_52: "Vellalaviduthi",
          PDS_53: "Valankondanviduthi",
          PDS_54: "Karuppatipatti",
          PDS_55: "Kattathi",
          PDS_56: "Nelliyadikollai",
          PDS_57: "Pattuviduthi",
          PDS_58: "Kaliyarayanviduthi",
          PDS_59: "Kadampatti",
          PDS_60: "Kilankadu",
          PDS_61: "Thattamanaipatti",
          PDS_62: "Keerathur",
          PDS_63: "Mudalipatti",
          PDS_64: "Kallumadai",
          PDS_65: "Selvanathapuram",
        },
      },
      Godown_ID07: {
        Godown_ID: 7,
        Godown: "Kulathur (Tk)",
        PDS_Shops: {
          PDS_1: "Keeranur Amutham",
          PDS_2: "Keeranur 1",
          PDS_3: "Keeranur 2",
          PDS_4: "Mosakudi",
          PDS_5: "Mangathevanpatti",
          PDS_6: "Nanjur",
          PDS_7: "Maruthur",
          PDS_8: "Pallathupatti",
          PDS_9: "Melapuduvayal",
          PDS_10: "Ilayavayal",
          PDS_11: "Kulathur",
          PDS_12: "Naduppatti",
          PDS_13: "Kalamavur",
          PDS_14: "Sengalur",
          PDS_15: "Kulavoipatti",
          PDS_16: "Kattukkottaipatti",
          PDS_17: "Palandampatti",
          PDS_18: "Lakxmanappatti",
          PDS_19: "Sivakamipuram",
          PDS_20: "Thennathiraiyanpatti",
          PDS_21: "T. Nallur",
          PDS_22: "Veerappatti",
          PDS_23: "Puliyur",
          PDS_24: "Vennamuthupatti",
          PDS_25: "Kayampatti",
          PDS_26: "Keelaiyur",
          PDS_27: "Vellaipillaiyarpatti",
          PDS_28: "Visalur",
          PDS_29: "Kannankudi",
          PDS_30: "Malaiyadipatti",
          PDS_31: "Killukkottai",
          PDS_32: "Killukkulavoipaatti",
          PDS_33: "Ulagakathanpatti",
          PDS_34: "Gunnandarkoil",
          PDS_35: "Udaiyalippatti",
          PDS_36: "Rakkathampatti",
          PDS_37: "Odugampatti",
          PDS_38: "Valiyampaatti",
          PDS_39: "Killanur",
          PDS_40: "Nallapudaiyanpatti",
          PDS_41: "Vathanakottai",
          PDS_42: "Perambur",
          PDS_43: "Periyathambiudaiyanpatti",
          PDS_44: "Sathinippatti",
          PDS_45: "Pongalappatti",
          PDS_46: "Andakkulam",
          PDS_47: "Veerakudi",
          PDS_48: "Kadambavayal",
          PDS_49: "Senaiyakkudi",
          PDS_50: "Vaithur",
          PDS_51: "Vaithikoil",
          PDS_52: "Mootampatti",
          PDS_53: "Seerangampatti",
          PDS_54: "Utchani",
        },
      },
      Godown_ID08: {
        Godown_ID: 8,
        Godown: "Manamelgudi (Tk)",
        PDS_Shops: {
          PDS_1: "Kilakudieruppu",
          PDS_2: "Amutham Manamelgudi",
          PDS_3: "Amutham Kottaipattinam",
          PDS_4: "Minnamozhi",
          PDS_5: "Perumaruthur",
          PDS_6: "Vellur Siruvarai",
          PDS_7: "Kattupiramanavayal",
          PDS_8: "Karkamalam",
          PDS_9: "Pillaiyarthidal",
          PDS_10: "Melasthanam",
          PDS_11: "Mumbalai",
          PDS_12: "Kandanivayal",
          PDS_13: "Kallakkuruchi",
          PDS_14: "Edayathimangalam",
          PDS_15: "Panavayal",
          PDS_16: "Subramaniapuram",
          PDS_17: "Nemmelivayal",
          PDS_18: "Ollanur",
          PDS_19: "Semmanampottal",
          PDS_20: "Ambalavananenthal",
          PDS_21: "Sathiyati",
          PDS_22: "Erattaiyalam",
          PDS_23: "Manamelkudi",
          PDS_24: "Athipattinam",
          PDS_25: "Ammapattinam",
          PDS_26: "Avudayar Pattinam-2",
          PDS_27: "Avudayarpattinam-I",
          PDS_28: "Vadakku Ammapattinam",
          PDS_29: "Manthangudi",
          PDS_30: "Thandalai",
          PDS_31: "Karakathikottai",
          PDS_32: "Melapapanur",
          PDS_33: "Vellur",
          PDS_34: "Nelveli",
          PDS_35: "Vannichipattinam",
          PDS_36: "Vichur",
          PDS_37: "Kolendram",
          PDS_38: "Meenavar Colony",
          PDS_39: "Kottaipattinam",
          PDS_40: "Kodikulam",
          PDS_41: "Pudukkudi",
          PDS_42: "Manjakudi",
          PDS_43: "Kodakudi",
          PDS_44: "Keelamanchakudi",
          PDS_45: "Sellanendal-1",
          PDS_46: "Alaganvayal",
          PDS_47: "Enathi",
          PDS_48: "Kilaravayal",
          PDS_49: "Vettivayal",
          PDS_50: "Periyamadaipatchal",
          PDS_51: "Seiyanam",
          PDS_52: "Ponnagaram",
          PDS_53: "Karakkottai",
          PDS_54: "Pillangudi",
          PDS_55: "Vinaitheertha Gopalapuram",
          PDS_56: "Pettivayal",
          PDS_57: "Singavanam",
          PDS_58: "Kottaipattinam South",
          PDS_59: "Neervilankulam",
          PDS_60: "Thirunallivayal",
          PDS_61: "Thinayakudi",
          PDS_62: "Koompallam",
          PDS_63: "Edayathur",
          PDS_64: "Gopalapuram",
          PDS_65: "Dharmarajanvayal",
          PDS_66: "Brahmanavayal",
          PDS_67: "Kambarkoil",
          PDS_68: "Mavilanganendal",
          PDS_69: "Sellappankottai",
          PDS_70: "Sudalaivayal",
          PDS_71: "Nilayur",
          PDS_72: "Sellanendal-2",
        },
      },
      Godown_ID09: {
        Godown_ID: 9,
        Godown: "Ponnamaravathi (Tk)",
        PDS_Shops: {
          PDS_1: "Ponnamaravathi-Amudam",
          PDS_2: "Valayapatti-Amudam",
          PDS_3: "Vegupatti-Amudam",
          PDS_4: "Thottiyampatti",
          PDS_5: "Ponnamaravathi-1",
          PDS_6: "Manappatti",
          PDS_7: "Ponnamaravathi-2",
          PDS_8: "Pon-Pudupatti-1",
          PDS_9: "Pon-Pudupatti-2",
          PDS_10: "Regunathapatti",
          PDS_11: "R-Palakurichi",
          PDS_12: "Kumarappatti",
          PDS_13: "Thirukalambur",
          PDS_14: "Karuppakudipattti",
          PDS_15: "Enathi",
          PDS_16: "Vendanpatti",
          PDS_17: "Varpattu",
          PDS_18: "Melasivapurai",
          PDS_19: "Nathupatti",
          PDS_20: "Alavayal",
          PDS_21: "Kesarapaati",
          PDS_22: "Kandiyanatham",
          PDS_23: "Karugapulampatti",
          PDS_24: "Thenur",
          PDS_25: "Semmalapatti",
          PDS_26: "Ammankurichi",
          PDS_27: "Nagarapatti",
          PDS_28: "Kallampatti",
          PDS_29: "Idayathur",
          PDS_30: "Maravamadurai",
          PDS_31: "Vellaiyakoundanpaatti",
          PDS_32: "Sathanur",
          PDS_33: "Arasamalai",
          PDS_34: "Karaiyur",
          PDS_35: "Mathiyani",
          PDS_36: "Alampatti",
          PDS_37: "Konnaiyanpatti",
          PDS_38: "Nallur",
          PDS_39: "Vellakudi-1",
          PDS_40: "Vellakudi-2",
          PDS_41: "Nerunchukudi",
          PDS_42: "Vazhakurichi",
          PDS_43: "Neiveli",
          PDS_44: "Cudalur",
          PDS_45: "Sithur",
          PDS_46: "Melathaniyam",
          PDS_47: "Keelathianiyam",
          PDS_48: "Oliyamangalam",
          PDS_49: "Mullipatti",
          PDS_50: "Soorapatti",
          PDS_51: "Avampatti",
          PDS_52: "Usilampatti",
          PDS_53: "Karanapatti",
          PDS_54: "Kalanivaipatti",
          PDS_55: "Sempoothi",
          PDS_56: "Melemelenilai",
          PDS_57: "Konnaiyur",
          PDS_58: "Moolangudi",
          PDS_59: "Thoothur",
          PDS_60: "Malayadipatti",
          PDS_61: "Sevalur",
          PDS_62: "Mekkinipatti",
          PDS_63: "Kovanur",
          PDS_64: "Sundram",
        },
      },
      Godown_ID10: {
        Godown_ID: 10,
        Godown: "Pudhukkottai (Tk)",
        PDS_Shops: {
          PDS_1: "Rajagopalapuram",
          PDS_2: "Santhanathapuram",
          PDS_3: "Rajagopalapuram-2",
          PDS_4: "Urban-20",
          PDS_5: "Urban-21",
          PDS_6: "T V S-1",
          PDS_7: "T V S-2",
          PDS_8: "Urban-1",
          PDS_9: "Urban-2",
          PDS_10: "Urban-3",
          PDS_11: "Urban-4",
          PDS_12: "Urban-5",
          PDS_13: "Urban-6",
          PDS_14: "Urban-7",
          PDS_15: "Urban-8",
          PDS_16: "Urban-9",
          PDS_17: "Urban-10",
          PDS_18: "Urban-11",
          PDS_19: "Urban-12",
          PDS_20: "Urban-13",
          PDS_21: "Urban-14",
          PDS_22: "Urban-15",
          PDS_23: "Urban-16",
          PDS_24: "Urban-17",
          PDS_25: "Urban-18",
          PDS_26: "Urban-19",
          PDS_27: "I T I Pallathuvayal",
          PDS_28: "Urban-22",
          PDS_29: "K S M Nagar",
          PDS_30: "Annachathiram",
          PDS_31: "Urban-23",
          PDS_32: "Urban-24",
          PDS_33: "Urban-25",
          PDS_34: "Urban-26",
          PDS_35: "Urban-28",
          PDS_36: "Urban-30",
          PDS_37: "Kavinadu West",
          PDS_38: "Kanakkanpatti",
          PDS_39: "Kavinadu Keelavattam",
          PDS_40: "Nathampannai",
          PDS_41: "Purakarai Nathampannai",
          PDS_42: "Sellukudi",
          PDS_43: "Mullur H.S",
          PDS_44: "Thennathiraiyanpatti",
          PDS_45: "Vagavasal",
          PDS_46: "Mullur Ncdc",
          PDS_47: "Rasapatti",
          PDS_48: "Thattampatti",
          PDS_49: "Idayapatti",
          PDS_50: "Kummupatti",
          PDS_51: "Kedayapatti",
          PDS_52: "Vadavalam",
          PDS_53: "Itchadi-1",
          PDS_54: "Itchadi-2",
          PDS_55: "Keelakayampatti",
          PDS_56: "Therku Chettiyapatti",
          PDS_57: "Sammattividuthi Nalroad",
          PDS_58: "Sammattividuthi",
          PDS_59: "B.Mathur",
          PDS_60: "Mookampatti",
          PDS_61: "Adanakkottai",
          PDS_62: "Kallukaranpatti",
          PDS_63: "Thondamanoorani",
          PDS_64: "Vannarapatti",
          PDS_65: "Chokkanathapatti",
          PDS_66: "Kuppayanpatti",
          PDS_67: "Karuppudayanpatti",
          PDS_68: "Ganapathipuram",
          PDS_69: "Sembattur",
          PDS_70: "Puthambur",
          PDS_71: "Kurichipatti",
          PDS_72: "Varapur",
          PDS_73: "Pulavankadu",
          PDS_74: "Valacheripatti",
          PDS_75: "Nemmelipatti",
          PDS_76: "Sundaneripatti",
          PDS_77: "Manaviduthi",
          PDS_78: "Koolaiyanviduthi",
          PDS_79: "Manthankudi",
          PDS_80: "Kammankadu Keelapatti",
          PDS_81: "Perungalur",
          PDS_82: "Mettupatti",
          PDS_83: "Ariyur",
          PDS_84: "Thirumalairayasamudram",
          PDS_85: "Samathuvapuram",
          PDS_86: "Mangalathupatti",
          PDS_87: "Vellavettanviduthi",
          PDS_88: "Chinnappanagar",
          PDS_89: "Ashok Nagar",
          PDS_90: "Uppupatti",
          PDS_91: "Subramaniyapuram Nagar Ngo Colony",
          PDS_92: "Kavinadu West-2",
        },
      },
      Godown_ID11: {
        Godown_ID: 11,
        Godown: "Thirumayam (Tk)",
        PDS_Shops: {
          PDS_1: "Konapattu Store",
          PDS_2: "Thirumayam",
          PDS_3: "Seemanur",
          PDS_4: "Azhagapuri.P",
          PDS_5: "Arimalam",
          PDS_6: "Samanthanvayal",
          PDS_7: "Samuthiram",
          PDS_8: "Agavayal",
          PDS_9: "Sirayampatti",
          PDS_10: "Mirattunilai",
          PDS_11: "Thanjur",
          PDS_12: "Keelapanaiyur",
          PDS_13: "Melur",
          PDS_14: "Osuvampatti",
          PDS_15: "Enapatti",
          PDS_16: "Pilivalam",
          PDS_17: "Sokkanathapatti",
          PDS_18: "Perunthurai",
          PDS_19: "Kottaiyur",
          PDS_20: "Senkeerai",
          PDS_21: "Oonaiyur",
          PDS_22: "Elanchavur",
          PDS_23: "Kannankarakudi",
          PDS_24: "R.R.Samuthiram",
          PDS_25: "Panangudi",
          PDS_26: "Kadiyapatti",
          PDS_27: "Vanniyulanthanvayal",
          PDS_28: "Kulathupatti",
          PDS_29: "Rayavaram",
          PDS_30: "Vengalur",
          PDS_31: "Athanur",
          PDS_32: "Aranmanaipatti",
          PDS_33: "Malaikudipatti",
          PDS_34: "Samathuvapuram",
          PDS_35: "Thulaiyanur",
          PDS_36: "K.Pallivasal",
          PDS_37: "Meyyapuram",
          PDS_38: "Pillamangalam",
          PDS_39: "Konapattu",
          PDS_40: "Adukapatti",
          PDS_41: "Neivasal",
          PDS_42: "Manjinipatti",
          PDS_43: "Elanapatti",
          PDS_44: "Seerathakudi",
          PDS_45: "T.Poovampatti",
          PDS_46: "Thekkattur",
          PDS_47: "Kadayakudi",
          PDS_48: "Neivasalpatti",
          PDS_49: "Perunkudi",
          PDS_50: "Melathemuthampatti",
          PDS_51: "Namanasamuthiram",
          PDS_52: "Poovampatti",
          PDS_53: "Valayampatti",
          PDS_54: "Munasanthai",
          PDS_55: "Nedungudi",
          PDS_56: "Puthunilaivayal",
          PDS_57: "Nampooranipatti",
          PDS_58: "Nallambalsamuthiram",
          PDS_59: "Piliyavayal",
          PDS_60: "K.Rayavaram",
          PDS_61: "Vadakattupatti",
          PDS_62: "Usilampatti",
          PDS_63: "Melnilaivayal",
          PDS_64: "Velavayal",
          PDS_65: "Karaiyapatti",
          PDS_66: "Kaikulanvayal",
          PDS_67: "Karamangalam",
          PDS_68: "Kalluukudiyiruppu",
          PDS_69: "Ponthupuli",
          PDS_70: "Kummangudi",
          PDS_71: "Keeranipatti",
          PDS_72: "Thuraiyur",
          PDS_73: "Anikkini",
          PDS_74: "Valaramanickam",
          PDS_75: "Meenikanda",
          PDS_76: "Thalayathivayal",
          PDS_77: "Kottur",
          PDS_78: "Kottur-Nachanthupatti",
          PDS_79: "Kulamangalam",
          PDS_80: "Rarapuram",
          PDS_81: "Kummankudi",
          PDS_82: "Nagarathupatti",
          PDS_83: "Lembalakudi",
          PDS_84: "Mallankudi",
          PDS_85: "Pilakkudipatti",
          PDS_86: "Arasanthampatti",
          PDS_87: "Peraiyur",
          PDS_88: "Virachilai-2",
          PDS_89: "Veeranampatti",
          PDS_90: "Virachilai-1",
          PDS_91: "Melapanaiyur-2",
          PDS_92: "Melapanaiyur-1",
          PDS_93: "Neikonam",
          PDS_94: "Sethurapatti",
          PDS_95: "V.Lakshmipuram",
          PDS_96: "Rangiyam",
          PDS_97: "Kannanur-2",
          PDS_98: "Kuruvikondanpatti",
          PDS_99: "Kulipirai",
          PDS_100: "Athur",
          PDS_101: "Kannanur-1",
          PDS_102: "Dhurvasapuram",
          PDS_103: "Onankudi",
          PDS_104: "Thekkur",
          PDS_105: "Sudanthirapuram",
          PDS_106: "Kallur",
          PDS_107: "N.Puthur",
        },
      },
      Godown_ID12: {
        Godown_ID: 12,
        Godown: "Viralimalai (Tk)",
        PDS_Shops: {
          PDS_1: "Viralimalai - 1",
          PDS_2: "Viralimalai - 2",
          PDS_3: "Viralimalai - 3",
          PDS_4: "Meboothakudi",
          PDS_5: "Poruvai",
          PDS_6: "Akkalnayakanpatti",
          PDS_7: "Vanathirayanpatti - 2",
          PDS_8: "Jeyamangalam",
          PDS_9: "Vanathirayanpatti - 1",
          PDS_10: "Kathalur",
          PDS_11: "Mullaiyur",
          PDS_12: "Kalkudi",
          PDS_13: "Samathuvapuram",
          PDS_14: "Vadukapatti",
          PDS_15: "Vittamapatti",
          PDS_16: "Komangalam",
          PDS_17: "Perumampatti",
          PDS_18: "Poothakudi - 2",
          PDS_19: "Poothakudi - 1",
          PDS_20: "Kodalikudi",
          PDS_21: "Kavarappatti",
          PDS_22: "Nambampatti",
          PDS_23: "Pattnapatti",
          PDS_24: "Rajalippatti",
          PDS_25: "Kodikalpatti",
          PDS_26: "Ramakoundanpatti",
          PDS_27: "Viralur",
          PDS_28: "Kulavaipatti",
          PDS_29: "Rajagiri",
          PDS_30: "Idaiyapatti",
          PDS_31: "Thengaithinnippatti",
          PDS_32: "Poyyamani",
          PDS_33: "Seralappatti",
          PDS_34: "Viruthappatti",
          PDS_35: "Kalappanur",
          PDS_36: "Poolangalam",
          PDS_37: "Kodumbalur",
          PDS_38: "Kasavanur",
          PDS_39: "Vellaiyakoundanpatti",
          PDS_40: "Meenaveli",
          PDS_41: "Sellampatti",
          PDS_42: "Agarappatti",
          PDS_43: "Madhurappatti",
          PDS_44: "Theravur",
          PDS_45: "Thennambadi",
          PDS_46: "Keelathottiyapatti",
          PDS_47: "Velur",
          PDS_48: "Kalimangalam",
          PDS_49: "Kunnathur",
          PDS_50: "Melapachakudi",
          PDS_51: "Kumarapatti",
          PDS_52: "Neerpalani",
          PDS_53: "Vemmani",
          PDS_54: "Malampatti",
          PDS_55: "Perambur",
          PDS_56: "Avuoor",
          PDS_57: "Amburpatti",
          PDS_58: "Suriyur",
          PDS_59: "Chithambur",
          PDS_60: "Alangudi",
          PDS_61: "Sengalakkudi",
          PDS_62: "Mathayanaipatti",
        },
      },
    },
  },

  Dis_ID21: {
    District_Name: "Sivagangai",
    Godowns: {
      Godown_ID01: {
        Godown_ID: 1,
        Godown: "Devakottai (Tk)",
        PDS_Shops: {
          PDS_1: "Tncsc-1",
          PDS_2: "Tncsc-2",
          PDS_3: "Tncsc-3",
          PDS_4: "Tncsc-4",
          PDS_5: "Tncsc-5",
          PDS_6: "Tncsc-6",
          PDS_7: "Tncsc-7",
          PDS_8: "Tncsc-8",
          PDS_9: "Tncsc-9",
          PDS_10: "Tncsc-10",
          PDS_11: "Tncsc-11",
          PDS_12: "Tncsc-12",
          PDS_13: "Perattukottai",
          PDS_14: "Sadayankadu",
          PDS_15: "Melasemponmari",
          PDS_16: "Vettaikaranpatti",
          PDS_17: "Aravayal",
          PDS_18: "Sirumaruthoor",
          PDS_19: "Thalaiyur",
          PDS_20: "Kodikottai",
          PDS_21: "Maviduthikkottai",
          PDS_22: "Kdagampatti",
          PDS_23: "Velimuthi",
          PDS_24: "Manjani",
          PDS_25: "Thachavayal",
          PDS_26: "Sathikottai",
          PDS_27: "Thalakkavayal",
          PDS_28: "Pidaranenthal",
          PDS_29: "Pudhukudi",
          PDS_30: "Selugai",
          PDS_31: "Eluvankottai",
          PDS_32: "THENNEERVAYAL",
          PDS_33: "ELOZHIVAYAL",
          PDS_34: "JEEVNAGAR",
          PDS_35: "Kottur",
          PDS_36: "Periyakarai",
          PDS_37: "Egaraikottavayal",
          PDS_38: "Nachangulam",
          PDS_39: "Velayuthapattinam",
          PDS_40: "Vethiyalangulam",
          PDS_41: "Puliyal",
          PDS_42: "Thidakkottai",
          PDS_43: "Pagayani",
          PDS_44: "Subramaniyapuram New Street",
          PDS_45: "Variyanvayal",
          PDS_46: "Sakkanthi",
          PDS_47: "Panangulam",
          PDS_48: "Samathuvapuram",
          PDS_49: "Nagadi",
          PDS_50: "Thirumanavayal",
          PDS_51: "Kallangudi",
          PDS_52: "Muppaiyur",
          PDS_53: "Karkalathur",
          PDS_54: "Paruthiyur",
          PDS_55: "Kannangudi",
          PDS_56: "Kappaloor",
          PDS_57: "Kumaramangalam",
          PDS_58: "Kandiyur",
          PDS_59: "K.Sriruvanoor",
          PDS_60: "Thathanicolony",
          PDS_61: "Poosalagudi",
          PDS_62: "Kalapangudi",
          PDS_63: "Kodagudi",
          PDS_64: "Anumanthakudi",
          PDS_65: "Sithanoor",
          PDS_66: "Ooravayal",
          PDS_67: "Periyaunjanai",
          PDS_68: "Chinnaunjanai",
          PDS_69: "Mangalam",
          PDS_70: "Vengaloor",
          PDS_71: "Thiruppakkottai",
          PDS_72: "Theralapur",
          PDS_73: "Kilamalai",
          PDS_74: "Kalathur",
          PDS_75: "Vadakeelkudi",
          PDS_76: "Kodikkulam",
          PDS_77: "Thuduppur",
          PDS_78: "Kumaraveloor",
          PDS_79: "Shanmuganathapattinam",
          PDS_80: "Ilangudi",
          PDS_81: "Siruvathi",
          PDS_82: "Sirunallur",
          PDS_83: "Anukkanenthal",
          PDS_84: "Sekkagudui",
          PDS_85: "Vilankattor",
          PDS_86: "Thiruvegampat",
          PDS_87: "Orasur",
          PDS_88: "Kulamangalam",
          PDS_89: "Keelauchani",
          PDS_90: "Sarugani",
          PDS_91: "Gobalapuram",
          PDS_92: "Vellikatti",
          PDS_93: "Uruvatti",
          PDS_94: "Nagaramangalam",
          PDS_95: "Ponnalikkottai",
          PDS_96: "Sengarkovil",
          PDS_97: "Kumani",
          PDS_98: "Kiliyur",
          PDS_99: "Annasalai",
        },
      },
      Godown_ID02: {
        Godown_ID: 2,
        Godown: "Illayangudi (Tk)",
        PDS_Shops: {
          PDS_1: "Pamco 1",
          PDS_2: "Pamco2",
          PDS_3: "Pamco3",
          PDS_4: "Pamco4",
          PDS_5: "Pamco5",
          PDS_6: "Pamco6",
          PDS_7: "Pamco7",
          PDS_8: "Pamco8",
          PDS_9: "Indiranagar",
          PDS_10: "Kongampatti",
          PDS_11: "Kelayoorcolony",
          PDS_12: "Vadavirukkai",
          PDS_13: "Alavidangan",
          PDS_14: "Visavanoor",
          PDS_15: "Sooranam",
          PDS_16: "Akkavayal",
          PDS_17: "Uthayanoor",
          PDS_18: "Kannamangalam",
          PDS_19: "Indangulam",
          PDS_20: "Karaikulam",
          PDS_21: "Madhava Nagar",
          PDS_22: "Meladuraiyoor",
          PDS_23: "Sathany",
          PDS_24: "Sothugudi",
          PDS_25: "Vallakulam",
          PDS_26: "Thayamangalam",
          PDS_27: "Uthamanoor",
          PDS_28: "Kalaikulam",
          PDS_29: "Thadiamangalam",
          PDS_30: "Devathakudi",
          PDS_31: "Vandal",
          PDS_32: "Muthur",
          PDS_33: "Nagamugunthankudi",
          PDS_34: "Vijayangudi",
          PDS_35: "Thiruvalloor",
          PDS_36: "Salaigramam",
          PDS_37: "Northsalaigramam",
          PDS_38: "Northsalaigramam",
          PDS_39: "Thugavoor",
          PDS_40: "Kattanoor",
          PDS_41: "Virayadhakandan",
          PDS_42: "Aranmanaikarai",
          PDS_43: "Kalangathankottai",
          PDS_44: "Aranaiyoor",
          PDS_45: "Nenjathoor",
          PDS_46: "Karumpukoottam",
          PDS_47: "Ariyandipuram",
          PDS_48: "Karunchuthi",
          PDS_49: "Kottaiyoor",
          PDS_50: "Puliyoor",
          PDS_51: "Southkeeranoor",
          PDS_52: "Munaivendry",
          PDS_53: "Melayoor",
          PDS_54: "Mulliyaranendal",
          PDS_55: "Nedungulam",
          PDS_56: "Katchathanaloor",
          PDS_57: "S Samuthiram",
          PDS_58: "Samuthiram",
          PDS_59: "Panjanoor",
          PDS_60: "Pudukottai",
          PDS_61: "Pramanakuruchi",
          PDS_62: "Kuruchi",
          PDS_63: "Keelanedoor",
          PDS_64: "Sathanoor",
          PDS_65: "Seevalathi",
          PDS_66: "Poolangudi",
          PDS_67: "Alimadurai",
          PDS_68: "Vani",
          PDS_69: "Nagarakudi",
          PDS_70: "Kumarakuruchi",
          PDS_71: "Perumbacheri",
          PDS_72: "A Thiru Udaiyarpuram",
          PDS_73: "A.Pudur",
          PDS_74: "Andagudi",
          PDS_75: "Kunappanendal",
          PDS_76: "Kombadi Madurai",
          PDS_77: "Ilamanoor",
          PDS_78: "Pudur",
          PDS_79: "Keelayoor",
          PDS_80: "Meyanendal",
          PDS_81: "Sirupalai",
          PDS_82: "Keelaikudi",
          PDS_83: "Sooriyankottai",
          PDS_84: "Kalladithidal",
        },
      },
      Godown_ID03: {
        Godown_ID: 3,
        Godown: "Kalaiyarkovil (Tk)",
        PDS_Shops: {
          PDS_1: "Kalaiyarkovil Pamco-1",
          PDS_2: "Kalaiyarkovil Pamco-2",
          PDS_3: "Maravamangalam Pamco-1",
          PDS_4: "Kalaiyarkovil Pamco-3",
          PDS_5: "Maravamangalam Pamco-2",
          PDS_6: "Nattarasankottai Society-1",
          PDS_7: "Nattarasankottai Society-2",
          PDS_8: "Nattarasankottai SCMS",
          PDS_9: "Gowripatti",
          PDS_10: "Allur",
          PDS_11: "Panangadi",
          PDS_12: "Soosaiyapparpattanam",
          PDS_13: "Sevalkanmai",
          PDS_14: "Arasakulam",
          PDS_15: "Paruthikanmoi",
          PDS_16: "Pulikanmai",
          PDS_17: "Andurani",
          PDS_18: "Silaiyaoorani",
          PDS_19: "Andichiurani",
          PDS_20: "Kalakanmai",
          PDS_21: "Mathukanmai",
          PDS_22: "Ottanam",
          PDS_23: "Nedunkulam",
          PDS_24: "Nedodai",
          PDS_25: "Moovarkanmoi",
          PDS_26: "Marathur",
          PDS_27: "Marakkathur",
          PDS_28: "Meppal",
          PDS_29: "Kollangudi",
          PDS_30: "Muthur",
          PDS_31: "Vittaneari",
          PDS_32: "Kanjipatti",
          PDS_33: "Pudhukeluvichi",
          PDS_34: "Ayyanarkulam",
          PDS_35: "Kandupatti",
          PDS_36: "Sengulam",
          PDS_37: "Udakulam",
          PDS_38: "Nadamangalam",
          PDS_39: "Utharapulli",
          PDS_40: "Mallal",
          PDS_41: "Sempanur",
          PDS_42: "Periyakannanur Pamco",
          PDS_43: "Sempar Pamco",
          PDS_44: "Allpattaviduthi Pamco",
          PDS_45: "Athapadakki SCMS",
          PDS_46: "Oyyavanthan SCMS",
          PDS_47: "Solavanthan",
          PDS_48: "Vettikulam",
          PDS_49: "Siramam",
          PDS_50: "Manthikanmoi",
          PDS_51: "Kallivayal",
          PDS_52: "Nandanur",
          PDS_53: "Velarenthal",
          PDS_54: "Siriyur",
          PDS_55: "Solaiyur",
          PDS_56: "Pullukkottai",
          PDS_57: "Samathuvapuram-Purasadiudaippu",
          PDS_58: "Mudikkarai",
          PDS_59: "Maranthai",
          PDS_60: "Sakkur",
          PDS_61: "Palur",
          PDS_62: "Kolanthi",
          PDS_63: "Ilanthakarai",
          PDS_64: "Sethur",
          PDS_65: "Kanjiram",
          PDS_66: "Silukkupatti",
          PDS_67: "Siruvelangudi",
          PDS_68: "Pidikulam",
          PDS_69: "Mudidhanai",
          PDS_70: "Vannikkudi",
          PDS_71: "Vembani",
          PDS_72: "Pallithammam",
          PDS_73: "Allivayal",
          PDS_74: "Valanai",
          PDS_75: "Ammapattinam",
          PDS_76: "Alagapuri",
        },
      },
      Godown_ID04: {
        Godown_ID: 4,
        Godown: "Karaikudi (Tk)",
        PDS_Shops: {
          PDS_1: "T N C S C - 1",
          PDS_2: "T N C S C - 2",
          PDS_3: "T N C S C - 3",
          PDS_4: "T N C S C - 4",
          PDS_5: "TNCSC-5",
          PDS_6: "Sekkalai 1",
          PDS_7: "Sekkalai 2",
          PDS_8: "Sangarapuram",
          PDS_9: "Pamco 2",
          PDS_10: "Amman Sannathi 1",
          PDS_11: "Amman Sannathi 2",
          PDS_12: "Santhapettai 1",
          PDS_13: "Santhapetai 2",
          PDS_14: "Muthupattinam 2",
          PDS_15: "R13-1",
          PDS_16: "R13-2",
          PDS_17: "R13-3",
          PDS_18: "Makkal Angadi 2",
          PDS_19: "Makkal Angadi-3",
          PDS_20: "Pari Nagar",
          PDS_21: "Cecri",
          PDS_22: "Alangagudiyar Theru 2",
          PDS_23: "Muthuramalingar Nagar",
          PDS_24: "Alangudiyar Theru 1",
          PDS_25: "K Velangudi",
          PDS_26: "Pallathur 1",
          PDS_27: "Pudhuvayal 1",
          PDS_28: "Vengavayal",
          PDS_29: "Pudhuvayal 2",
          PDS_30: "Pudhuvayal 3",
          PDS_31: "Chettinadu",
          PDS_32: "Kanadukathan",
          PDS_33: "Nemathanpatti",
          PDS_34: "Indira Nagar",
          PDS_35: "Kallal 1",
          PDS_36: "Marungipatti",
          PDS_37: "Kallal 2",
          PDS_38: "Pattanampatti",
          PDS_39: "Sevarakottai",
          PDS_40: "Alangudi",
          PDS_41: "Nesavalarcolony",
          PDS_42: "Sangamthidal",
          PDS_43: "Koviloor",
          PDS_44: "Manapatti",
          PDS_45: "Kallupatti",
          PDS_46: "Sr Pattinam",
          PDS_47: "Sathampathi",
          PDS_48: "Visalayankottai",
          PDS_49: "Pallathur 2",
          PDS_50: "Water Tank",
          PDS_51: "Anna Nagar",
          PDS_52: "Parupoorani",
          PDS_53: "Burma Colony",
          PDS_54: "Ngo Colony",
          PDS_55: "Sivan Kovil",
          PDS_56: "Subramaniyapuram",
          PDS_57: "Kotheri",
          PDS_58: "PALLATHUR-3",
          PDS_59: "Vairavapuram",
          PDS_60: "Pamco I",
          PDS_61: "Pamco III",
          PDS_62: "Pamco IV",
          PDS_63: "Pamco V",
          PDS_64: "Lakshminagar",
          PDS_65: "Pamco VI",
          PDS_66: "Alagappapuram",
          PDS_67: "Kottaiyur 1",
          PDS_68: "Kottaiyur 2",
          PDS_69: "K Algapuri",
          PDS_70: "Peyanpatti",
          PDS_71: "O Siruvayal",
          PDS_72: "Chokalingapudur",
          PDS_73: "Avudaipoigai",
          PDS_74: "Thiruvelangudi",
          PDS_75: "Lakshmipuram",
          PDS_76: "Kothamangalam",
          PDS_77: "Manachai",
          PDS_78: "Tholkappiyar Nagar",
          PDS_79: "Ariyakudi",
          PDS_80: "Samathuvapuram",
          PDS_81: "Amaravathipudur",
          PDS_82: "Kandanoor",
          PDS_83: "Palaiyur",
          PDS_84: "Kulapadi",
          PDS_85: "Palaveethi-1",
          PDS_86: "Melamanakudi",
          PDS_87: "Birundakudi",
          PDS_88: "Kamalai",
          PDS_89: "Periyakottai",
          PDS_90: "Jeyamkondan",
          PDS_91: "Amanapatti",
          PDS_92: "Enchavayal",
          PDS_93: "Pukkudi",
          PDS_94: "Nattucheri",
          PDS_95: "Ambakudi",
          PDS_96: "Pirambuvayal",
          PDS_97: "Sirugavayal",
          PDS_98: "Mathur",
          PDS_99: "Mitravayal",
          PDS_100: "Periyakotakudi",
          PDS_101: "Koomachipatti",
          PDS_102: "Sembanoor",
          PDS_103: "Melapoongudi",
          PDS_104: "Keelapoongudi",
          PDS_105: "Muthupatti",
          PDS_106: "Puliyangudipatti",
          PDS_107: "Aranamanisiruvayal",
          PDS_108: "Kodunkulam",
          PDS_109: "Alampattu",
          PDS_110: "Kurunthampattu",
          PDS_111: "Veppankulam",
          PDS_112: "Natarajapuram",
          PDS_113: "Panangudi",
          PDS_114: "Vetriyur",
          PDS_115: "A.Karunkulam",
          PDS_116: "Satharasanpatti",
          PDS_117: "Kurangalipatti",
          PDS_118: "Malaikandan",
          PDS_119: "Pallavangudi",
          PDS_120: "Athankudi",
          PDS_121: "Patharakudi",
          PDS_122: "Kuthaloor",
          PDS_123: "Keeranipatti",
          PDS_124: "Managiri",
          PDS_125: "Thalakkavoor",
          PDS_126: "Pilar",
          PDS_127: "Poiyalur",
          PDS_128: "Padathanpatti",
          PDS_129: "Illupakkudi",
          PDS_130: "Sirugapatti",
          PDS_131: "Peerkalaikadu",
          PDS_132: "Pethachikudiyiruppu",
          PDS_133: "Mithirangudi",
          PDS_134: "Mulangadu",
          PDS_135: "A V P L Street",
          PDS_136: "Nerpugapatti",
          PDS_137: "Nangapatti",
          PDS_138: "Surakudi",
          PDS_139: "Athankudi-2",
          PDS_140: "Kottaiyur 3",
        },
      },
      Godown_ID05: {
        Godown_ID: 5,
        Godown: "Manamadurai (Tk)",
        PDS_Shops: {
          PDS_1: "Manamadurai Shop No - 9",
          PDS_2: "Manamadurai Shop No - 3",
          PDS_3: "Manamadurai Shop No - 6",
          PDS_4: "Manamadurai Shop No - 5",
          PDS_5: "Manamadurai Shop No - 2",
          PDS_6: "Aathanoor Salai",
          PDS_7: "Udaikulam",
          PDS_8: "Vellalar Street",
          PDS_9: "Maravar Street",
          PDS_10: "Moonkiloorani",
          PDS_11: "Kompukaranendal",
          PDS_12: "Theethanpettai",
          PDS_13: "Perumpacheri",
          PDS_14: "Milaganoor",
          PDS_15: "Kattikulam",
          PDS_16: "Kuvalaiveli",
          PDS_17: "Arasakulam",
          PDS_18: "Senthatiyendal",
          PDS_19: "K Pudukulam",
          PDS_20: "Annavasal",
          PDS_21: "Kelamelgudi",
          PDS_22: "Kilankattur",
          PDS_23: "M Karisalkulam",
          PDS_24: "Rajakampeeram",
          PDS_25: "Thuthikulam",
          PDS_26: "K.Pudur",
          PDS_27: "Kalpiravu",
          PDS_28: "Idaikattur",
          PDS_29: "Velur",
          PDS_30: "Pappankulam",
          PDS_31: "Sirugudi",
          PDS_32: "Anniyendal",
          PDS_33: "Vagudi",
          PDS_34: "Chinnakannanoor",
          PDS_35: "Melapasalai",
          PDS_36: "Arimandapam",
          PDS_37: "Keelapasalai",
          PDS_38: "Vedhiyarendal",
          PDS_39: "Mankulam",
          PDS_40: "Panikkanendal",
          PDS_41: "Therkusandanoor Kudiyiruppu",
          PDS_42: "Therkusandanoor",
          PDS_43: "Vadakusandanoor",
          PDS_44: "Maruthanganaloor",
          PDS_45: "S. Karaikudi",
          PDS_46: "T Alankulam",
          PDS_47: "Melapidavoor",
          PDS_48: "Keelapidavoor",
          PDS_49: "K Perunkarai",
          PDS_50: "T Pudukottai",
          PDS_51: "Alampacheri",
          PDS_52: "Melanettur",
          PDS_53: "P Alankulam",
          PDS_54: "Konnakulam",
          PDS_55: "Soorakulam",
          PDS_56: "Kumilandavu",
          PDS_57: "Nathapurakki",
          PDS_58: "Samathuvapuram",
          PDS_59: "Seikalathur",
          PDS_60: "Manampakki",
          PDS_61: "Thanjakoor",
          PDS_62: "Vellikuruchi",
          PDS_63: "Vilathur",
          PDS_64: "Sullankudi",
          PDS_65: "Thamaraikudi",
          PDS_66: "Periyaavankadu",
          PDS_67: "Muthanendal",
        },
      },
      Godown_ID06: {
        Godown_ID: 6,
        Godown: "Singampunari (Tk)",
        PDS_Shops: {
          PDS_1: "Singampunari -I",
          PDS_2: "Singampunari -II",
          PDS_3: "Singampunari- III",
          PDS_4: "Singampunari IV",
          PDS_5: "Singampunari V",
          PDS_6: "Singampunari VI",
          PDS_7: "Singampunari VII",
          PDS_8: "Singampunari-VIII",
          PDS_9: "Aralikottai",
          PDS_10: "NValayapatti",
          PDS_11: "Eriyur",
          PDS_12: "Vadavanpatti",
          PDS_13: "Mallakottai",
          PDS_14: "DMampatti",
          PDS_15: "S Mampatti",
          PDS_16: "N Mampatti",
          PDS_17: "Aralipatti",
          PDS_18: "M Vaiyapuripatti",
          PDS_19: "SKovilpatti",
          PDS_20: "M Surakudi",
          PDS_21: "M Ayyapatti",
          PDS_22: "Kallampatti",
          PDS_23: "AKalapur",
          PDS_24: "Anaikarapatti",
          PDS_25: "Kirungakottai",
          PDS_26: "Vengaipatti",
          PDS_27: "Kannamangalappatti",
          PDS_28: "SV Mangalam",
          PDS_29: "Kayampatti",
          PDS_30: "Oduvanpatti",
          PDS_31: "Piranmalai",
          PDS_32: "SMettupatti",
          PDS_33: "Sirumarudhur",
          PDS_34: "Melappatti",
          PDS_35: "Nainapatti",
          PDS_36: "SSevalpatti",
          PDS_37: "S Mathur",
          PDS_38: "Jeyankondanilai",
          PDS_39: "Karisalpatti",
          PDS_40: "Ganapathipatti",
          PDS_41: "Nagamangalam",
          PDS_42: "Chettikurchi",
          PDS_43: "Dharmapatti",
          PDS_44: "Kondapalayam",
          PDS_45: "KAmmappatti",
          PDS_46: "Valaisaipatti",
          PDS_47: "Musundapatti",
          PDS_48: "Ulagampatti",
          PDS_49: "Manthakudipatti",
          PDS_50: "SPudur",
          PDS_51: "Vellaiyakudipatti",
          PDS_52: "Neduvayal",
          PDS_53: "Urathupatti",
          PDS_54: "Kulathupatti",
          PDS_55: "Kilavayal",
          PDS_56: "Varappur",
          PDS_57: "Melavannariruppu",
          PDS_58: "Kattukkudipatti",
          PDS_59: "MKovilpatti",
          PDS_60: "Muraiyur",
          PDS_61: "KPudupatti",
          PDS_62: "K L Pudupatti",
          PDS_63: "Vagutheluvanpatti",
          PDS_64: "Sivapuripatti",
          PDS_65: "Kunnathur",
          PDS_66: "Puluthipatti",
          PDS_67: "AKallapur No 2",
          PDS_68: "Kirungakottai-2",
          PDS_69: "Ulagampatti",
          PDS_70: "Piranmalai-2",
        },
      },
      Godown_ID07: {
        Godown_ID: 7,
        Godown: "Sivagangai (Tk)",
        PDS_Shops: {
          PDS_1: "Tncsc-I",
          PDS_2: "Tncsc-II",
          PDS_3: "Tncsc-III",
          PDS_4: "Arasanoor Samathuvapuram",
          PDS_5: "Amudham Angadi - 4",
          PDS_6: "TNCSC-6",
          PDS_7: "Sivagangai Main 1",
          PDS_8: "Sivagangai Main 2",
          PDS_9: "Scms I",
          PDS_10: "Sasthiri Theru",
          PDS_11: "Scms II",
          PDS_12: "Scms III",
          PDS_13: "Nehru Bajar",
          PDS_14: "Komalipatti",
          PDS_15: "Pasaangarai",
          PDS_16: "Sakanthi",
          PDS_17: "Mudikandam",
          PDS_18: "Senthiudaiyanathapuram",
          PDS_19: "Thamarakki (North)",
          PDS_20: "Thamarakki (South)",
          PDS_21: "Kumarapatti",
          PDS_22: "Kandankipatti",
          PDS_23: "Indira Nagar",
          PDS_24: "Ngo-I",
          PDS_25: "Ngo-II",
          PDS_26: "Michaelpattinam",
          PDS_27: "Pudhukulam",
          PDS_28: "Vembathur",
          PDS_29: "Arulanthapuram",
          PDS_30: "Keelamangalam",
          PDS_31: "Melamangalam",
          PDS_32: "Surakkulam",
          PDS_33: "T.Puddur",
          PDS_34: "Koothandan",
          PDS_35: "Vaniyankudi",
          PDS_36: "Vandhavasi",
          PDS_37: "Keelakandani",
          PDS_38: "Sundaranadappu",
          PDS_39: "K.Nedunkulam",
          PDS_40: "Vembankudi",
          PDS_41: "Muthupatti",
          PDS_42: "Veeravalsai",
          PDS_43: "Kottakudi",
          PDS_44: "Pillur",
          PDS_45: "Kovanoor",
          PDS_46: "Panaiur",
          PDS_47: "Managudi",
          PDS_48: "Okkur",
          PDS_49: "O puthur",
          PDS_50: "Karungalakudi",
          PDS_51: "Solapuram",
          PDS_52: "Veerapatti",
          PDS_53: "Keelapoongudi",
          PDS_54: "Thirumanpatti",
          PDS_55: "Melapoongudi",
          PDS_56: "Namanoor",
          PDS_57: "Thajanpudhupatti",
          PDS_58: "Madhakupatti",
          PDS_59: "Periya Ammachipatti",
          PDS_60: "Alavakottai",
          PDS_61: "Perungudi",
          PDS_62: "Al-Usilampatti",
          PDS_63: "Alagammanagari",
          PDS_64: "Thirumalai",
          PDS_65: "Periyakottaipatti",
          PDS_66: "Pongundupatti",
          PDS_67: "Kattanipatti",
          PDS_68: "Kalarathinipatti",
          PDS_69: "Esanoor",
          PDS_70: "Velangapatti",
          PDS_71: "Idayamelur",
          PDS_72: "Keelachaloor",
          PDS_73: "Saloor",
          PDS_74: "Sivalpatti",
          PDS_75: "Kooturavupatti",
          PDS_76: "Okappatti",
          PDS_77: "Kannimarpatti",
          PDS_78: "Malampatti",
          PDS_79: "Alakichipatti",
          PDS_80: "Nalukottai",
          PDS_81: "Gandhinagar",
          PDS_82: "Puthupatti",
          PDS_83: "Kilathari",
          PDS_84: "Ilupakkudi",
          PDS_85: "Arasanoor",
          PDS_86: "Maraniusilankulam",
          PDS_87: "Sempur",
          PDS_88: "Kalloorani",
          PDS_89: "Pacheari",
          PDS_90: "Mathur",
          PDS_91: "Ilanthangudi",
          PDS_92: "Kanur",
          PDS_93: "Kannayiruppu",
          PDS_94: "Padamathur",
          PDS_95: "Kamarajar Colony",
          PDS_96: "Illuppakudi",
          PDS_97: "Kanjirangal",
          PDS_98: "Mutharasan",
          PDS_99: "Mangudi",
          PDS_100: "Kayangulam",
          PDS_101: "Seerambatti",
          PDS_102: "Periyakottai",
          PDS_103: "Paganeari",
          PDS_104: "Kadaneari",
          PDS_105: "Nagarampatti",
          PDS_106: "Maangattupatti",
          PDS_107: "Ammanpatti",
          PDS_108: "Kovilpatty",
          PDS_109: "Kaththapaddu",
          PDS_110: "Kottuthuraipatti",
          PDS_111: "Allavilampatti",
          PDS_112: "Sadaiyanpatti",
          PDS_113: "Keelakottai",
          PDS_114: "Nariyankudi",
          PDS_115: "Silanthangudi",
          PDS_116: "Pravalur",
          PDS_117: "Sithaloor",
          PDS_118: "Paiyur Samathuvapuram",
          PDS_119: "Palayavalavu",
          PDS_120: "Senthamil Nagar",
        },
      },
      Godown_ID08: {
        Godown_ID: 8,
        Godown: "Thiruppattur (Tk)",
        PDS_Shops: {
          PDS_1: "Tncsc - Thenmapattu",
          PDS_2: "Vaniyampatti",
          PDS_3: "c Main 1",
          PDS_4: "Thiruppattur Main 2",
          PDS_5: "Thiruppattur Main 3",
          PDS_6: "R-9 I",
          PDS_7: "R-9 II",
          PDS_8: "Palayavalavu",
          PDS_9: "Kandavarayanpatti",
          PDS_10: "Vaikalathur",
          PDS_11: "Kavanur",
          PDS_12: "Paiyur",
          PDS_13: "KVairavanpatti",
          PDS_14: "Mahibalanpatti",
          PDS_15: "Kandaramanicam",
          PDS_16: "Valayapatti",
          PDS_17: "Kongaratty",
          PDS_18: "Thiruppathur Main IV",
          PDS_19: "Thiruppattur Main V",
          PDS_20: "Thiruppattur Main VI",
          PDS_21: "Thiruppattur Main VII",
          PDS_22: "Thiruppattur Main-8",
          PDS_23: "Poolnakurichi",
          PDS_24: "Sevvur",
          PDS_25: "Nerkuppai I",
          PDS_26: "Priyamaruthipatti",
          PDS_27: "Nerkuppai II",
          PDS_28: "Thuvar",
          PDS_29: "Ranasingapuram",
          PDS_30: "Thirvudaiyarpatti",
          PDS_31: "Kottaiyiruppu",
          PDS_32: "Sunnamiruppu",
          PDS_33: "Karuppur",
          PDS_34: "Nattarmangalam",
          PDS_35: "Manamelpatti",
          PDS_36: "Nedumaram",
          PDS_37: "Sirukoodalpatti",
          PDS_38: "Sullankudi",
          PDS_39: "MPudur",
          PDS_40: "T Vairavanpatti",
          PDS_41: "Piramanapatti",
          PDS_42: "Vadamavali",
          PDS_43: "Thevarampur",
          PDS_44: "Sowmiyanarayanapuram",
          PDS_45: "Kattampur",
          PDS_46: "Thirukkalapatti",
          PDS_47: "Mangudi",
          PDS_48: "Karaiyur",
          PDS_49: "Alampatti",
          PDS_50: "Mathavarayanpatti",
          PDS_51: "Vanginipatti",
          PDS_52: "Olukamangalam",
          PDS_53: "Mithilaipatti",
          PDS_54: "Thirukolakudi",
          PDS_55: "Keelasevalpatti-I",
          PDS_56: "Acharampatti",
          PDS_57: "Keelaseevalpatti-II",
          PDS_58: "Ammapatti",
          PDS_59: "Nagapanpatti",
          PDS_60: "Senbagampettai",
          PDS_61: "Santhirampatti",
          PDS_62: "Ilayathangudi",
          PDS_63: "Keeranipatti",
          PDS_64: "Aavanipatti",
          PDS_65: "AVelangudi",
          PDS_66: "PKarunkulam",
          PDS_67: "Patamangalam",
          PDS_68: "Nadvikottai",
          PDS_69: "Kallipattu",
          PDS_70: "Perichikovil",
          PDS_71: "Veliyathur",
          PDS_72: "Kundrakudi",
          PDS_73: "Thattatti",
          PDS_74: "KAthangudi",
          PDS_75: "N Vairavanpatti",
          PDS_76: "Nemam",
          PDS_77: "Pillayarpatti",
          PDS_78: "Siravayal",
          PDS_79: "Nachiyapuram",
          PDS_80: "Ilankudi",
          PDS_81: "Koothakudi",
          PDS_82: "Kambanur",
          PDS_83: "Thenkarai",
          PDS_84: "Manakkudi",
          PDS_85: "Sevinipatti",
          PDS_86: "Konnathanpatti",
          PDS_87: "TPudupatti",
          PDS_88: "Samathuvapuram",
          PDS_89: "AThekkur",
          PDS_90: "Aathirampatti",
          PDS_91: "Ayenipatti",
          PDS_92: "Muthur",
          PDS_93: "V Malampatti",
          PDS_94: "Poolankuruchi-2",
        },
      },
      Godown_ID09: {
        Godown_ID: 9,
        Godown: "Thiruppuvanam  (Tk)",
        PDS_Shops: {
          PDS_1: "Melachokkanathiruppu",
          PDS_2: "Piramanur",
          PDS_3: "Thiruppuvanam Main -1",
          PDS_4: "Thiruppuvanam Kottai-1",
          PDS_5: "Thiruppuvanam Kottai-2",
          PDS_6: "Thiruppuvanam Pudur -1",
          PDS_7: "Thiruppuvanam Pudur -2",
          PDS_8: "Vaigai Vadakarai",
          PDS_9: "Madappuram",
          PDS_10: "A.Vellakarai",
          PDS_11: "Allinagaram",
          PDS_12: "Vaviyarenthal",
          PDS_13: "Panayanenthal",
          PDS_14: "Nainar Pettai",
          PDS_15: "Kaliyanthur",
          PDS_16: "Valayanenthal",
          PDS_17: "Thiruppuvanam Kottai-3",
          PDS_18: "Thiruppuvanam Ward -5 6",
          PDS_19: "Nelmudikarai-1",
          PDS_20: "Manaloor",
          PDS_21: "T.Athikarai",
          PDS_22: "Agaram",
          PDS_23: "Thattankulam",
          PDS_24: "Kalukerkadai",
          PDS_25: "Malavarayanenthal",
          PDS_26: "Thiruppachetti",
          PDS_27: "T.Pappankulam",
          PDS_28: "T.Velankulam",
          PDS_29: "Thoothai",
          PDS_30: "Sampirayanenthal",
          PDS_31: "Saluppanodai-2",
          PDS_32: "Saluppanodai",
          PDS_33: "T.Parayankulam",
          PDS_34: "Ladanenthal",
          PDS_35: "Muduvanthidal",
          PDS_36: "Mela Chorikulam",
          PDS_37: "Keelachorikulam",
          PDS_38: "Kothankulam",
          PDS_39: "Melarangium Mahalir",
          PDS_40: "Konthagai",
          PDS_41: "Keeladi",
          PDS_42: "Melavellore",
          PDS_43: "Mangudi",
          PDS_44: "Ambalathadi",
          PDS_45: "Palayanur",
          PDS_46: "Veeranenthal",
          PDS_47: "Sangankulam",
          PDS_48: "Vallarenthal",
          PDS_49: "S.Vagaikulam",
          PDS_50: "Maranadu",
          PDS_51: "Kaluvankulam",
          PDS_52: "D.Karisalkulam",
          PDS_53: "Pottapalayam",
          PDS_54: "Pattam",
          PDS_55: "Sottathatti",
          PDS_56: "Sayanapuram",
          PDS_57: "Jaripudukottai",
          PDS_58: "Kanjirakulam",
          PDS_59: "Senkulam",
          PDS_60: "Mukkudi",
          PDS_61: "Keelapoovanthi",
          PDS_62: "Poovanthi",
          PDS_63: "Enathisevel",
          PDS_64: "Enathi",
          PDS_65: "Theli",
          PDS_66: "K.Pethanenthal",
          PDS_67: "Kannakkangudi",
          PDS_68: "Pappakudi",
          PDS_69: "Vayalseri",
          PDS_70: "Nelmudikari-2",
          PDS_71: "Pasiyapuram",
          PDS_72: "Villiyarenthal",
          PDS_73: "Vannikottai",
          PDS_74: "Kattamankottai",
          PDS_75: "Kodathupatti",
          PDS_76: "Keelarangium",
          PDS_77: "Muniyandipuram",
          PDS_78: "Thiruppachetti-Mahalir",
          PDS_79: "Ilandaikulam - Women",
        },
      },
    },
  },
  Dis_ID22: "Madurai",
  Dis_ID23: "Theni",
  Dis_ID24: "Virudhunagar",
  Dis_ID25: "Ramanathapuram",
  Dis_ID26: "Tuticorin",
  Dis_ID27: "Tirunelveli",
  Dis_ID28: "Kanyakumari",
  Dis_ID29: "Dharmapuri",
  Dis_ID30: "Krishnagiri",
  Dis_ID31: "Coimbatore",
  Dis_ID32: "Tiruppur",
  Dis_ID33: "Tenkasi",
  Dis_ID34: "Kallakurichi",
  Dis_ID35: "Ranipet",
  Dis_ID36: "Tirupathur",
  Dis_ID37: "Chengalpet",
  Dis_ID38: "Mayiladuthurai",
};

export default FINALFORMATE;
